In [1]:
fruits = ['apple','mango','guava']

In [2]:
fruits

['apple', 'mango', 'guava']

In [3]:
type(fruits)

list

In [4]:
a_list = [23,'hello',None,3.14,fruits,3<=5]

In [5]:
a_list

[23, 'hello', None, 3.14, ['apple', 'mango', 'guava'], True]

In [6]:
empty_list = []

In [7]:
empty_list

[]

In [8]:
print('number of fruits:',len(fruits))

number of fruits: 3


In [9]:
len(a_list)

6

In [10]:
len(empty_list)

0

In [11]:
fruits[0]

'apple'

In [12]:
fruits[1]

'mango'

In [13]:
fruits[2]

'guava'

In [14]:
fruits[3]

IndexError: list index out of range

In [15]:
fruits[-1]

'guava'

In [17]:
fruits[-2]

'mango'

In [18]:
fruits[-3]

'apple'

In [19]:
fruits[-4]

IndexError: list index out of range

In [20]:
a_list[2:5]

[None, 3.14, ['apple', 'mango', 'guava']]

In [21]:
a_list[2:10]

[None, 3.14, ['apple', 'mango', 'guava'], True]

In [22]:
a_list[12:10]

[]

In [23]:
a_list[:2]

[23, 'hello']

In [24]:
a_list[:5]

[23, 'hello', None, 3.14, ['apple', 'mango', 'guava']]

In [25]:
a_list[-2:-5]

[]

In [26]:
a_list[-5:-2]

['hello', None, 3.14]

In [27]:
a_list[5:1]

[]

In [28]:
a_list[2:]

[None, 3.14, ['apple', 'mango', 'guava'], True]

In [29]:
a_list[-6:0]

[]

In [30]:
fruits

['apple', 'mango', 'guava']

In [31]:
fruits[1]='mango'

In [32]:
fruits

['apple', 'mango', 'guava']

In [33]:
fruits

['apple', 'mango', 'guava']

In [34]:
fruits.insert(1,'banana')

In [35]:
fruits

['apple', 'banana', 'mango', 'guava']

In [36]:
fruits.remove('mango')

In [37]:
fruits

['apple', 'banana', 'guava']

In [38]:
fruits.pop(1)

'banana'

In [39]:
fruits

['apple', 'guava']

In [40]:
fruits.pop()

'guava'

In [41]:
fruits

['apple']

In [7]:
w1,w2,w3=0.3,0.2,0.5

In [8]:
kanto_tem = 73
kanto_rainfall = 67
kanto_humidity = 43

In [9]:
kanto_yield_apples = kanto_tem*w1+kanto_rainfall*w2+kanto_humidity*w3
kanto_yield_apples

56.8

In [10]:
kanto = [73,67,43]
johto = [91,88,64]
hoenn = [87,134,58]
sinonh = [102,43,37]
unova = [69,96,70]

In [11]:
weights = [w1,w2,w3]

In [14]:
def crop_yield(region,weights):
    result = 0
    for x, w in zip(region,weights):
        result += x*w    #RESULT +X*W
    return result

In [15]:
crop_yield(johto,weights)

76.9

In [16]:
crop_yield(kanto,weights)

56.8

In [17]:
crop_yield(hoenn,weights)

81.9

In [18]:
#install pip
!python  -m pip install --upgrade pip

ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\anand\Anaconda3\lib\site-packages\pip\_vendor\urllib3\response.py", line 438, in _error_catcher
    yield
  File "C:\Users\anand\Anaconda3\lib\site-packages\pip\_vendor\urllib3\response.py", line 519, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "C:\Users\anand\Anaconda3\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 62, in read
    data = self.__fp.read(amt)
  File "C:\Users\anand\Anaconda3\lib\http\client.py", line 462, in read
    n = self.readinto(b)
  File "C:\Users\anand\Anaconda3\lib\http\client.py", line 506, in readinto
    n = self.fp.readinto(b)
  File "C:\Users\anand\Anaconda3\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\anand\Anaconda3\lib\ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\anand\Anaconda3\lib\ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
soc

In [19]:
!pip -v


Usage:   
  pip <command> [options]

Commands:
  install                     Install packages.
  download                    Download packages.
  uninstall                   Uninstall packages.
  freeze                      Output installed packages in requirements format.
  list                        List installed packages.
  show                        Show information about installed packages.
  check                       Verify installed packages have compatible dependencies.
  config                      Manage local and global configuration.
  search                      Search PyPI for packages.
  cache                       Inspect and manage pip's wheel cache.
  index                       Inspect information available from package indexes.
  wheel                       Build wheels from your requirements.
  hash                        Compute hashes of package archives.
  completion                  A helper command used for command completion.
  debug                    

In [20]:
#pip install python packages in any environment
!pip install numpy --upgrade --quite --user


Usage:   
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: --quite


In [21]:
import numpy as np

In [22]:
kanto = np.array([73,67,43])

In [23]:
kanto

array([73, 67, 43])

In [24]:
weights = np.array([w1,w2,w3])

In [25]:
weights

array([0.3, 0.2, 0.5])

In [26]:
weights[0]

0.3

In [27]:
weights[2]

0.5

In [28]:
kanto[2]

43

In [29]:
np.dot(kanto,weights)

56.8

In [30]:
johto

[91, 88, 64]

In [31]:
np.dot(johto,weights)

76.9

In [35]:
sinnoh=np.array([102,43,37])

In [36]:
sinnoh

array([102,  43,  37])

In [37]:
np.dot(sinnoh,weights)

57.699999999999996

In [38]:
unova=np.array([69,96,70])

In [39]:
unova

array([69, 96, 70])

In [40]:
np.dot(unova,weights)

74.9